name: portfolio
description: "Hello! I am Felipe, a passionate electronic engineer with experience in mobile, AI and web development. My portfolio showcases my creativity, technical skills and featured projects. Explore and discover what I can do for you! 💼 #Portfolio #Creativity"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^13.2.3
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  timelines: ^0.1.0
  flutter_svg: ^2.0.10+1
  timezone: ^0.9.2
  dropdown_search: ^5.0.6
  flutter_feather_icons: ^2.0.0+1
  table_calendar: ^3.1.1
  intl: ^0.19.0
  footer: ^0.0.4
  emojis: ^0.9.9
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
